-- insert into tb_marcas(nome, ativo) Values ("Nick", true)
-- select * from tb_marcas
-- insert into tb_marcas(nome, ativo) Values ("Fatal Surf", false)
-- select * from tb_marcas
-- update tb_marcas set nome="Fatal Surf", ativo=true 
-- where id=2;
-- select * from tb_marcas
-- select * from tb_marcas where id <> 2 busca só diferente de 2
-- select nome from tb_marcas
-- delete from tb_marcas where id = 3 deleta item
-- select * from tb_marcas
-- INSERT INTO tb_marcas (nome, ativo) VALUES ("Nike", true);
-- INSERT INTO tb_marcas (nome, ativo) VALUES ("H&M", true);
-- INSERT INTO tb_marcas (nome, ativo) VALUES ("Zara", true);
-- INSERT INTO tb_marcas (nome, ativo) VALUES ("Louis Vuitton", true);
-- INSERT INTO tb_marcas (nome, ativo) VALUES ("Adidas", true);
-- INSERT INTO tb_marcas (nome, ativo) VALUES ("Uniqlo", true);
-- INSERT INTO tb_marcas (nome, ativo) VALUES ("Hermès", true);
-- INSERT INTO tb_marcas (nome, ativo) VALUES ("Rolex", true);
-- INSERT INTO tb_marcas (nome, ativo) VALUES ("Gucci", true);
-- INSERT INTO tb_marcas (nome, ativo) VALUES ("Cartier", true);
-- INSERT INTO tb_marcas (nome, ativo) VALUES ("Polo", true);
-- INSERT INTO tb_marcas (nome, ativo) VALUES ("Armany", true);
-- select * from tb_marcas
-- select * from tb_marcas where nome like "%fa%"
-- select * from tb_marcas where ativo=true
